### ISSUE TITLE
`static`, `php` を選択した時に、 .gitignore がインストールされない

### ISSUE THREAD

**Issue by mtmtkzm** [liginc/lig-interactive-generator#10]
特に、  `static` の方は、
https://github.com/liginc/laravel-mix-boilerplate-static/blob/master/.gitignore
をそのままもってくるようにしたい

**Comment by mtmtkzm** [comment]
https://github.com/liginc/lig-interactive-generator/issues/11

の方針解決をしてから、
引数にオプションを渡すのがもっとも手っ取り早そう！
（設定項目があるのありがたい........... 🙏  @ryotamoriyama

**Comment by ghost** [comment]
https://github.com/liginc/lig-interactive-generator/pull/24
これで解決のはず。

**Comment by ghost** [comment]
@mtmtkzm 解決！
