### ISSUE TITLE
download  error

### ISSUE THREAD

**Issue by ShoShindo** [liginc/lig-interactive-generator#26]
lig
? Choose Environment Type wordpress
? Type Project( You can use only a-z0-9 and "-") testtest
? Type WordPress version (Empty will be "latest") 
? Type PHP version (Empty will be "7.3") 
? Type MySQL version (Empty will be "5.7") 
⠋ [download] https://github.com/liginc/lig-docker-wordpress.gitxcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by ghost** [comment]
犯人これ
http://shsm385.hatenablog.com/entry/2019/10/28/153724
