### ISSUE TITLE
body直下にSVGの記述がない

### ISSUE THREAD

**Issue by ShoShindo** [liginc/lig-interactive-generator#28]
以下の記述
`<?php echo file_get_contents(get_stylesheet_directory() . '/assets/svg/sprite.svg'); ?>`

**Comment by ghost** [comment]
@ShoShindo これはどういうことだろ？？

**Comment by ghost** [comment]
こっちじゃなくて
https://github.com/liginc/lig-wordpress-template/blob/master/header.php
ここかな。
