### ISSUE TITLE
laravel-mix-boilerplate-wordpressのバージョンが最新でない

### ISSUE THREAD

**Issue by ShoShindo** [liginc/lig-interactive-generator#6]
最新にする

**Comment by lig-dsktschy** [comment]
このPRをマージしていただくと、master＝最新が取り込まれるようになるはずです。
https://github.com/liginc/lig-interactive-generator/pull/9

**Comment by mtmtkzm** [comment]
@ShoShindo @lig-dsktschy 
#9 マージされたので、npm publish して動作確認できれば閉じれますかねー🤓

**Comment by mtmtkzm** [comment]
close! 🙏  @ShoShindo @ryotamoriyama @lig-dsktschy
